### ISSUE TITLE
onTap ?

### ISSUE THREAD

**Issue by vptcnt** [SM-SHIFAT/banner_listtile#3]
Hello,

How to implement onTap with BannerListTitle ?

I tried 
```dart
Material(
  child: InkWell(
    onTap: () { /* ... */ },
    child: BannerListTile( /* ... */ ),
  ),
),
```

But the ripple effect is behind the BannerListTitle

Thanks for your help

**Comment by SM-SHIFAT** [comment]
Ripple effect does not work here because it contains Material widget data in it. 
 But i will update it as soon as i can in the next update. 
 Tnx for letting me know the issue.
